### ISSUE TITLE
Who will update it so we know issues are resolved?

### ISSUE THREAD

**Issue by robdyke** [open-health-hub/TPP-SystmOne-Issue-Tracker#3]
Mike Smith [said](https://twitter.com/drmikedsmith/status/1081456381071368192) 

> This is a wonderful idea. Who will update it so we know issues are resolved? And are @TPP_SystmOne listening?

**Comment by robdyke** [comment]
Take a look at the proposed template for [creating a new issue](https://github.com/pacharanero/TPPSystmOne/blob/fb1943604f3033ecc3899c80106a13a46d31eb59/.github/ISSUE_TEMPLATE/bug_report.md).

With an issue template, we can customize and standardize the information you'd like contributors to include when they open issues. See also [About issue and pull request templates](https://help.github.com/articles/about-issue-and-pull-request-templates/)

**Comment by pacharanero** [comment]
we will update it
the community will update it
TPP will (I hope) update it
